Repository wsmd/react-use-form-state, pull requests merged in 2019-04, with the labels that each got.

#53 Add `.errors` to typescript types.
  README.md
  src/index.d.ts
  test/types.tsx
Labels: under review

#54 Add support for custom components via `raw` input type
  README.md
  src/constants.js
  src/index.d.ts
  src/parseInputArgs.js
  src/useFormState.js
  src/utils.js
  test/useFormState-input.test.js
  test/useFormState-validation.test.js
Labels: enhancement

#61 Follow-Up Updates for raw input type
  README.md
  jest.setup.js
  package.json
  src/constants.js
  src/index.d.ts
  src/parseInputArgs.js
  src/useFormState.js
  src/utils.js
  test/types.tsx
  test/useFormState-input.test.js
  yarn.lock
Labels: bug

#63 Improve type safety of StateValues/StateValidity keys
  src/index.d.ts
  test/types.tsx
Labels: bug

#65 Improve types for BaseInputProps #64
  src/index.d.ts
Labels: enhancement, under review
